services:
  arcane:
    container_name: arcane
    image: ghcr.io/getarcaneapp/manager:latest
    restart: unless-stopped

    env_file:
      - ../../runtime/arcane/.env

    environment:
      TZ: "Asia/Jakarta"

    ports:
      - "3552:3552"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../runtime/arcane/data:/app/data

    networks:
      - private-net

    cgroup: host

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 1G

networks:
  private-net:
    external: true
