services:
  ytzero:
    container_name: ytzero
    image: ghcr.io/pelski/ytzero:latest
    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - ../../runtime/ytzero/data:/data

    networks:
      - private-net

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 2G

networks:
  private-net:
    external: true
