services:
  scrapling:
    container_name: scrapling
    image: ghcr.io/d4vinci/scrapling:latest
    restart: unless-stopped

    # env_file:
    #   - ../../runtime/scrapling/.env

    ports:
      - "8083:8083"

    volumes:
      - ../../runtime/scrapling/data:/app/data

    networks:
      - private-net

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

networks:
  private-net:
    external: true
